[package]
distribution = "2201.10.0"
org = "ballerinax"
name = "tableau"
version = "@toml.version@"
license = ["Apache-2.0"]
authors = ["Ballerina"]
keywords = [] # TODO: Add keywords
icon = "icon.png" 
repository = "https://github.com/ballerina-platform/module-ballerinax-tableau"

[build-options]
observabilityIncluded = true

[platform.java17]
graalvmCompatible = true
